version: "3.3"
services:
  web:
    build: ./web_app
    ports:
      - "80:3000"
    environment:
      HOST: api
    links:
      - api

  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URL: mongodb://mongodb:27017/test?authSource=admin
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
