image: docker:latest
services:
  - docker:dind
stages:
  - build
  # - deploy
before_script:
  - echo `pwd` # debug
  - docker login -u subtawee14 -p $PASSWORD
cache:
  paths:
    - node_modules/
build_image:
  stage: build
  script:
    - docker build -t subtawee14/node-ts:1.0.0 .
    - docker push subtawee14/node-ts:1.0.0

# docker-compose:
#   stage: deploy
#   before_script:
#     - apk add --no-cache py-pip
#     - pip install docker-compose~=1.23.0
#     - apk add --update curl && rm -rf /var/cache/apk/*
#   script:
#     - docker-compose -H $DOCKER_HOST pull
#     - docker-compose -H $DOCKER_HOST down
#     - docker-compose -H $DOCKER_HOST up -d
